services:
    backend:
        build: 
            context: .
        command: gunicorn --bind 0.0.0.0:8000 --reload proj.wsgi
        ports: 
            - 8000:8000
        volumes:
            - .:/opt/beertracker
        environment: 
            DJANGO_DEBUG: "true"
            DJANGO_DATABASE_URL: "postgres://beertracker:beertracker@database/postgres"
    database:
        image: postgres
        volumes:
            - dbdata:/var/lib/postgresql/data
        environment: 
            POSTGRES_USER: beertracker
            POSTGRES_PASSWORD: beertracker
            POSTGRES_DB: beertracker

volumes: 
    dbdata: